### ISSUE TITLE
Multisets as AbstractDict

### ISSUE THREAD

**Issue by ablaom** [scheinerman/Multisets.jl#2]
Nice package.

Curious why  `Multiset{K}` is not a subtype of `AbstractDict{K,Int64}`. It appears to implement that interface.

**Comment by scheinerman** [comment]
I didn’t think of it! I’ll try to remember to make that modification. (I’m not a programming pro … just a math person trying to build tools for my projects.) Thanks for the idea!

**Comment by scheinerman** [comment]
**Update**: I finally got around to looking at this issue and I see that a `Multiset` is a subtype of `AbstractSet` (I forgot I did that). I don't think Julia allows multiple inheritance so I don't think I can make it also a subtype of `AbstractDict`.

While the implementation of `Multiset` may provide all the necessary methods to allow it to be an `AbstractDict`, logically/mathematically, a `Multiset` is a kind of collection (a type of set) rather than an association between things. 

So I prefer to leave it as a subtype of `AbstractSet`.
